import Link from "next/link";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "Next JS",
//   description: "Generated by Next JS",
// };

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next JS",
    template: "Next JS | %s",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <p>Header</p>
          <Link href="/">Home</Link>
          <Link href="/about">About page</Link>
          <Link href="/products" replace>Products</Link>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}